name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t registry.mathieu-symphorien.fr/caille-fort-api-caillefort-api:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker registry
        run: echo "t" | docker login registry.mathieu-symphorien.fr --username "t" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag registry.mathieu-symphorien.fr/caille-fort-api-caillefort-api:latest registry.mathieu-symphorien.fr/caille-fort-api-caillefort-api:latest
          docker push registry.mathieu-symphorien.fr/caille-fort-api-caillefort-api:latest
